on:
  pull_request:
  push:
    branches: ["main"]

concurrency:
  cancel-in-progress: true
  group: test-${{ github.ref }}

jobs:
  pre-commit:
    name: Run full linting on project using pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          npm ci

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        env:
          SKIP: no-commit-to-branch

  tests:
    name: Run full test suite

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          npm ci

      - name: Run tests
        run: |
          npm test
